### ISSUE TITLE
3.0.1 version breaks build, documentation should be updated to reflect changes

### ISSUE THREAD

**Issue by PrashamTrivedi** [infinum/android_dbinspector#11]
For previous versions, we were adding DbInspector activity in our manifests. In 3.0.1 the activity is added in library manifest, which breaks build when we upgrade the library from old version (1.1) to latest(3.0.1). However android studio is kind enough to tell us about `tools:replace` node. Isn't it good to update readme to reflect this change?

Also, having same label ( `android:label="@string/dbinspector_app_name"`) and icon (`android:icon="@drawable/dbinspector_ic_launcher"`) will likely to create confusion if more than one app uses this library as there will be more than one launcher icons which will have same icon and label/.

Please update readme to reflect these things.

**Comment by reisub** [comment]
Hi @PrashamTrivedi,
I updated the README to include instructions for upgrading 1.x->2.x and 2.x->3.x.

About the label and icon, I'm not sure what your concern is. Each app can set it's own icon and label for the DbInspector launcher icon. If those are not set, defaults are used. Please read the README again and let me know how you think we can make it more clear.

**Comment by PrashamTrivedi** [comment]
>  Each app can set it's own icon and label for the DbInspector launcher icon. If those are not set, defaults are used.
I missed that in readme. It would be better if it has it's own section. Anyways current readme has sufficient information for everything, thus closing this issue.
