### ISSUE TITLE
Database chooser doesn't show db with name without extension

### ISSUE THREAD

**Issue by danikula** [infinum/android_dbinspector#14]
My database has name like `my-app-db` and hasn't extension. As result database helper doesn't show my database in list of databases.

version 3.0.1

**Comment by reisub** [comment]
Hi @danikula,
thanks for reporting this.
It's fixed with commit https://github.com/infinum/android_dbinspector/commit/7465c9c5f15d9ab53bfa0ea05dec823d2597fe74 and pushed to maven central with version `3.1.0`.
It should be synced to maven central in the next couple of hours.

**Comment by danikula** [comment]
@reisub, thanks for super quick fix! Now db chooser works fine.
