### ISSUE TITLE
Table filtering

### ISSUE THREAD

**Issue by danikula** [infinum/android_dbinspector#15]
It will be extremely helpful to add ability to execute sql queries or just filter tables by simple conditions, like `media_type equals 'audio'`

**Comment by reisub** [comment]
This is actually on the roadmap for the next version so hang tight. I can't
give you an exact timeframe, but we should have it ready in a month or so.

**Comment by reisub** [comment]
Just a quick update. @zplesac is working on this on a separate branch (enhancement/crud_live_actions), but I have no idea when he'll be able to finish it.
