### ISSUE TITLE
Support view and triggers displaying

### ISSUE THREAD

**Issue by mariotaku** [infinum/android_dbinspector#16]
It would be nice if we can see views (content and creation statement), and triggers.

**Comment by reisub** [comment]
We'll see what we can do.
If you have an idea how to do it and the time to do it, feel free to open a pull request :)

**Comment by mariotaku** [comment]
no problem, I'll try :)

**Comment by reisub** [comment]
@mariotaku any luck with this?
@zplesac do you have an idea how to do this?

**Comment by zplesac** [comment]
@reisub @mariotaku Views and triggers are stored in sql_master database file. You can get them like this:

SELECT name, tbl_name FROM sqlite_master WHERE type='trigger';

SELECT sql FROM sqlite_master WHERE type = 'view';

I'll check if we can obtain them using raw SQL statements in Android code.
