### ISSUE TITLE
DbInspector only can be opened when may app has been killed.

### ISSUE THREAD

**Issue by w4lle** [infinum/android_dbinspector#27]
1.my app is opening
2.click DbInspector

not open DbInspector but open my app again.
can u fix it ,thx

**Comment by reisub** [comment]
Hi @w4lle,

this issue was fixed a while ago and this morning we released DbInspector `3.2.0` to maven which includes this fix. It might take a while for it to show up in search on maven central, but you can start using it within the hour.
