### ISSUE TITLE
Whether the project supports custom paths

### ISSUE THREAD

**Issue by hush881025** [infinum/android_dbinspector#28]
Whether the project supports custom paths ， Example: DB save to SD card

**Comment by reisub** [comment]
This functionality is not supported at this time, but you are welcome to
open a pull request :-)

On Tue, Jul 21, 2015, 06:19 hush881025 <notifications@github.com> wrote:

> Whether the project supports custom paths ， Example: DB save to SD card
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinum/android_dbinspector/issues/28>.
>
-- 
Dino Kovač
Infinum Ltd.

mail: dino.kovac@infinum.hr
phone: +385 95 911 6324
web: http://www.infinum.co/
