### ISSUE TITLE
Build error after updating Android support libs to v23.2

### ISSUE THREAD

**Issue by MarcBernstein** [infinum/android_dbinspector#32]
Using
```
compile 'com.android.support:support-v4:23.2.0'
compile 'com.android.support:appcompat-v7:23.2.0'
```
along with
`debugCompile 'im.dino:dbinspector:3.2.2@aar'`

results in the build error:
```
:app:processDebugResources
/Users/dino/android/dbinspector/dbinspector/src/main/res/menu/dbinspector_fragment_table_list.xml:13: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/abc_ic_menu_copy_mtrl_am_alpha').
/Users/dino/android/dbinspector/dbinspector/src/main/res/menu/dbinspector_fragment_table_list.xml:21: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/abc_ic_menu_share_mtrl_alpha').

 FAILED
```

If I revert back to `23.1.1` for the support libs, the issue goes away.

**Comment by reisub** [comment]
Hi Marc,
thanks for the report.
Looks like some icons we use from the support lib were removed or renamed.

Fixing this should be as simple as copying over those icons into the project and replacing the references in this file:
https://github.com/infinum/android_dbinspector/blob/master/dbinspector/src/main/res/menu/dbinspector_fragment_table_list.xml

If you can make a PR to fix this, we can have a bugfix release out pretty fast. If not, I'll try to fix it later this week.

**Comment by MarcBernstein** [comment]
@reisub PR submitted: https://github.com/infinum/android_dbinspector/pull/33

**Comment by chandru9279** [comment]
Please do a release that includes this fix.

**Comment by reisub** [comment]
@chandru9279 this was released with version 3.2.3. Can you check if it works for you?

**Comment by chandru9279** [comment]
With 3.2.3 I still get an error while building
```
Error:No resource found that matches the given name (at 'icon' with value '@drawable/abc_ic_search_api_mtrl_alpha').
Error:Execution failed for task ':app:processDevDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/zasz/Library/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
```

**Comment by MarcBernstein** [comment]
FWIW, with `compile 'com.android.support:support-v4:23.2.0'` and `debugCompile 'im.dino:dbinspector:3.2.3@aar'` I do not see the issue you mentioned @chandru9279. I confirmed by changing the dbinspector version to 3.2.2 and then a `./gradlew cleanAssembleDebug` to verify that the issue exists in 3.2.2 but not in 3.2.3.

Could you do a clean first to make sure that perhaps caching isn't coming into play here?

**Comment by imtiazkalamabir** [comment]
Hi, the error is due to change in icon name in android drawable resource. For example, in the recent version the search icon exists as '**abc_ic_commit_search_api_mtrl_alpha**' and '**abc_ic_go_search_api_material**' rather than 'abc_ic_search_api_mtrl_alpha'. Therefore replacing the icon value with the new icon name should solve the problem.
