### ISSUE TITLE
Option to delete content of table

### ISSUE THREAD

**Issue by ignaciotcrespo** [infinum/android_dbinspector#35]
There could be great to have an option to clean a table, or a specific row. Is it on the roadmap?

**Comment by reisub** [comment]
Hi @ignaciotcrespo, this was being worked on branch enhancement/crud_live_actions by @zplesac.
However, currently work has stopped due to a lack of time.

@zplesac can tell you how far along he got with it, if you by any chance want to work on it :)

**Comment by ignaciotcrespo** [comment]
I checked the branch and has lot of changes, if you want I can add quickly an option to clear a table and create a pull request

**Comment by reisub** [comment]
Sure, that makes sense. Let me know if you need any help!

**Comment by reisub** [comment]
This was released with 3.3.0
