### ISSUE TITLE
Import existing database file

### ISSUE THREAD

**Issue by sparkitny** [infinum/android_dbinspector#41]
Hello,

thanks for developing the library. It's very useful. One Feature I currently Need is the Import of an existing database file. It doesn't matter which file Explorer I use, my db isn't exported. What am I doing wrong?

**Comment by reisub** [comment]
Hi @sparkitny,

which Android version are you using? Any more details you can provide?
@dmarin actually implemented this feature, maybe he has a tip?

**Comment by dmarin** [comment]
Hi @sparkitny, can you give us more details? A stacktrace would also be appreciated

**Comment by reisub** [comment]
I believe this i related to #42 so closing in favor of that one.
