### ISSUE TITLE
kv_default does not show meaningful data

### ISSUE THREAD

**Issue by andredoubleu** [infinum/android_dbinspector#49]
Hi I've been recently evaluating Couchbase Lite for my company's apps, and I think the android db inspector is a pretty cool concept to inspect the contents of our apps's dbs when debugging.  But I can't seem to view any meaningful data about my database.  In the version and body columns all it shows me is the word (data), like so:

![couchbase](https://user-images.githubusercontent.com/9728568/37121163-5973cbae-222a-11e8-8f5f-88bcee9324eb.png)

I guess I expected it to show me the key/value pairs for each document within the db.  Am I missing something?

**Comment by reisub** [comment]
Hi @andredoubleu, `(data)` should be shown only in case the column type is BLOB (binary data). If you change the dropdown at the top to view the structure of the table you should be able to verify that.

I'm don't know what the `kv_default` represents so I can't further interpret the data, but here's a wild guess - maybe the data is encrypted and saved as binary data?

**Comment by andredoubleu** [comment]
Hey, thanks for the response.   The screenshot above was taken from a basic sample app that I made to quickly test creating a database, adding a few documents, and performing a few basic queries.  I didn't enable any of the encryption properties on my Database or DatabaseConfiguration objects, and I didn't add any custom encryption to my payloads.  If it helps, here are the specific versions of the libraries that I'm using in my build.gradle file:

`implementation "com.couchbase.lite:couchbase-lite-android:2.0.0-DB022" // For Couchbase Lite.
debugImplementation "im.dino:dbinspector:3.4.1@aar" // For Couchbase Lite DB Inspector.`

Since you said you didn't know what kv_default was, I thought maybe there was something I misconfigured in my sample app, but then I downloaded the [ToDo Sample App](https://github.com/couchbaselabs/mobile-training-todo/tree/feature/2.0) and added the line:

`debugImplementation "im.dino:dbinspector:3.4.1@aar" // For Couchbase Lite DB Inspector.`

to my build.gradle file so that I could check out that database as well, and it also had the same 4 lines, android_metadata, kvmeta, kv_default, and kv_info:

![device-2018-03-08-103304](https://user-images.githubusercontent.com/9728568/37159762-a01f322c-22bc-11e8-8470-ddb8aa3c56e3.png)

And kv_default still showed all the bodies as blob data.

**Comment by andredoubleu** [comment]
Oh my bad -- The Couchbase Lite's github page linked to your Android DB Inspector project [here](https://github.com/couchbase/couchbase-lite-android/wiki#tools) and I assumed the two projects were maintained by the same people.  Sorry about that.
