### ISSUE TITLE
Crash when used in AndroidX project

### ISSUE THREAD

**Issue by mariciv** [infinum/android_dbinspector#57]
Currently, it is neccessary to also add implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0' depndecy to an AndroidX project. 

Without the dependency, DB inspector can't resolve  LocalBroadcastManager and this will cause a crash when you try to access your DB.

**Comment by reisub** [comment]
Fixed in version 4.0.0 which was just published, thanks for the bug report!
