### ISSUE TITLE
Using unstable dependencies by library

### ISSUE THREAD

**Issue by jakoss** [infinum/android_dbinspector#59]
## :writing_hand: Describe the bug
For now - version 5.0.0 seems great, but it's based on fragmentx 1.3.0.beta, which is unstable. After upgrading your library to newest version i got a handful of deprecation notices. I'm not really fond of using unstable libraries from google at production applications, so this is a killer problem for me here. Could you consider sticking with stable libraries for stable library releases? A lot of libraries are doing unstable releases and in those releases they can use unstable dependencies too (FlowBinding for example)

**Comment by bojankoma** [comment]
Thank you for using DbInspector. 
I understand your point, but I have to say that some of the 5.x.y features aren't possible without the alpha or beta AndroidX libraries.
I'll hastily update DbInspector on each dependency update until they reach a stable final version.
For now, I cannot do much besides advise to keep using 4.0.0 version until this condition is met.
I'll also keep this issue open until we reach that point and keep you informed.

**Comment by jakoss** [comment]
Awesome, i'm just fine with 4.0.0 for now. Hope fragmentx 1.3 will be released as stable shortly

**Comment by bojankoma** [comment]
Tracking this actively and as far as I can see, we are at RC stage now.
I see no major problems so far in the library so updated dependencies including RC variants will be implemented in next release.
Of course, we are still aiming at completely final and stable dependencies.

**Comment by jakoss** [comment]
Just an info for somebody that encounters exception: `java.lang.IllegalStateException: no event down from INITIALIZED`

There's a serious error with fragment-ktx:1.3.0-rc01 : https://stackoverflow.com/questions/63240530/fatal-exception-java-lang-illegalstateexception-no-event-down-from-initialized

Downgrading to earlier beta fixes this issue

**Comment by bojankoma** [comment]
@jakoss I haven't encounter this issue myself, but it seems valid.
Fragment 1.3.0 is now a stable release. I've updated dependencies in 5.2.4 version.
Can you test it out with the stable version, please?

For full stability at this time, we have Paging3 and RecyclerView in beta, while Datastore is in alpha.
This issue is still ongoing and will not be closed yet.

**Comment by jakoss** [comment]
Stable release is working great, thanks!

**Comment by bojankoma** [comment]
Today we are looking only at Paging3 in beta status, RecyclerView in RC and Datastore in alpha. 
I think it's safe to ignore Datastore for now but I'm monitoring these other two for stable releases.

This issue is still ongoing and will not be closed yet.

**Comment by bojankoma** [comment]
As of now, 5.3.0 uses stable RecyclerView version. Paging3 is still in beta status and Datastore is still in alpha.
Due to migration from jCenter to MavenCentral, Koin has changed into beta status too.

This issue is still ongoing and will not be closed yet.

**Comment by bojankoma** [comment]
As of now, 5.3.2 uses Paging3 that is still in RC status and Datastore is still in beta.
Koin has migrated to stable 3.0.1 release status.

This issue is still ongoing and will not be closed yet.

**Comment by bojankoma** [comment]
As of 5.3.6 only Datastore is in RC status with rc01.

This issue is still ongoing and will not be closed yet.

**Comment by bojankoma** [comment]
As of 5.3.8 all dependencies have reached stable.
