### ISSUE TITLE
Collapse large cell entries by default, add "expand" functionality

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android_dbinspector#62]
## :warning: Please describe your feature request
If the database contains some very long entry (e.g., a JSON response), it can make the entire view very difficult to navigate.

## :bulb: Describe the solution you'd like
I propose a certain character limit after which the entry in a cell would be collapsed by default, with an option to expand it (by tapping the cell or pressing some sort of "Expand" or "Show more" button).

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by bojankoma** [comment]
Decided to go in a different direction, a "system wide" cell limitation of lines and truncate.
Once again, this does not affect nor format any data differently, just the UI cell is presented  as preselected in persisted settings.
