### ISSUE TITLE
Table not refreshed after being updated through the SQL editor

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android_dbinspector#88]
## :writing_hand: Describe the bug
If you execute an SQL query which modifies the table, when you return to the table in question, it will still show old data. Refreshing it manually works, though.

## :bomb: Steps to reproduce
1. Go to an example table.
2. Press the "Edit" button
3. Execute a query that modifies that table (e.g., DELETE FROM example_table)
4. Return back to the table

## :wrench: Expected behavior
The table should be automatically refreshed. Ideally, it would refresh the table only if a modifying command on that table was executed, but I think it's fine to have a more broad trigger (e.g., any non-select command on any table was executed); I don't think the refresh action is too problematic.

**Comment by bojankoma** [comment]
@JonatanPlesko I'll leave the PR open for you in case you are intrigued by the solution of this bug.
Fix has been deployed and is available in 5.3.3 release.
