### ISSUE TITLE
Cannot use 5.4.0

### ISSUE THREAD

**Issue by jakoss** [infinum/android_dbinspector#97]
## :writing_hand: Describe the bug
Trying to use 5.4.0 ends up with:
```
Execution failed for task ':app:processDebuggableDevDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:C:\Users\Jakub\.gradle\caches\transforms-3\35bca2fadd1db3e7a978d8a5f1446405\transformed\dbinspector-5.4.0\res\values\values.xml:346:5-351:13: AAPT: error: style attribute 'android:attr/windowBlurBehindEnabled' not found.
         
     ERROR:C:\Users\Jakub\.gradle\caches\transforms-3\35bca2fadd1db3e7a978d8a5f1446405\transformed\dbinspector-5.4.0\res\values\values.xml:346:5-351:13: AAPT: error: style attribute 'android:attr/windowBlurBehindRadius' not found.
```

**Comment by bojankoma** [comment]
@jakoss Can you help me out here please with more data?
Like SDK versions on the project you are integrating DbInspector with?
5.4.0 is mostly about Android 12 adoption and you are not missing out if you need to use a previous version that works for you.
Until I fix it.

**Comment by jakoss** [comment]
Sure, i'm targeting and compiling with sdk 30. So i guess it's reasonable that this attribute isn't found. And i'm not sure if this can be managed with backwards compatibility since (AFAIK) there is no androidX library that offers compat attributes for that

**Comment by bojankoma** [comment]
@jakoss Thanks, that was helpful. I was able to reproduce it quickly.
You were right, I was way too eager to upgrade and release without proper backwards compatibility support. 
I believe following version 5.4.1 has it all fixed, so please try and let me know.

**Comment by jakoss** [comment]
@bojankoma works like a charm now, thanks!
